### ISSUE TITLE
Unable to leave a comment

### ISSUE THREAD

**Issue by samwilson** [mauris/mauris.github.io#1]
I was trying to leave a comment on https://mauris.github.io/posts/2022-04-05-utterances-blog-comments#comments

but got the following console error:

> Uncaught (in promise) TypeError: (destructured parameter).data is undefined
>    z NextJS

----

I was going to say:

> I thought it would be a straightforward copy-paste, but TypeScript came complaining about repo being an invalid attribute for the <script> tag.

It's possible to use `data-repo=foo/bar` instead, to make it valid.

(Although it looks like you're now using Giscus instead.)

**Comment by mauris** [comment]
hey @samwilson, appreciate the issue report. Yes I have switched over to Giscus since it had better integration and features over utterances. Thanks for sharing about `data-repo`!

I'll share a little bit about what "better integration and features" entails in another update post. 

🥂
